version: "3.9"
services:
  authentication:
    container_name: authentication
    build: ./authentication
    env_file:
      - ./authentication/.env
    ports:
      - "3000:3000"
    volumes:
      - ./authentication/src:/authentication/src
    entrypoint: [ "npm", "run", "start:dev" ]
  product:
    container_name: product
    build: ./product
    env_file:
      - ./product/.env
    ports:
      - "3001:3001"
    volumes:
      - ./product/src:/product/src
    entrypoint: [ "npm", "run", "start:dev" ]
    