apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: kruuux/product:1.0.2
          volumeMounts:
            - mountPath: /product/data
              name: product-volume
          command: ["npm", "run", "start:prod"]
          env: 
            - name: PRODUCT_SERVICE_PORT
              value: "3001"        
            - name: AUTHENTICATION_SERVICE_URL
              value: "http://authentication-service.default:3000"        
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: product-volume
          emptyDir: {}
            