apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector: 
    app: authentication
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000